"""Diagnostics Center and release-qualified generated-file Recycle Bin verification UI."""
from __future__ import annotations

import os
import tkinter as tk
from pathlib import Path
from tkinter import filedialog, messagebox, ttk

from . import i18n
from .diagnostics import (
    RecycleVerification,
    RecycleVerificationError,
    build_diagnostics_snapshot,
    inspect_recycle_support,
    load_recycle_verification,
)
from .gui import BG
from .recycle_evidence import (
    REPORT_NAME,
    _require_runtime_safety_contract,
    create_restore_evidence,
    move_restore_evidence,
    validate_restore_evidence_report,
    verify_restore_evidence,
)
from .release_attestation import (
    ATTESTATION_NAME,
    PackagedAttestationError,
    write_packaged_attestation,
)
from .space_hunter_gui import PhotoCleanApp as SpaceHunterPhotoCleanApp


DIAG_EN = {
    "Centrum diagnostyki…": "Diagnostics Center…",
    "Centrum diagnostyki": "Diagnostics Center",
    "Ctrl+Shift+D": "Ctrl+Shift+D",
    "Przegląd": "Overview",
    "Kosz Windows": "Windows Recycle Bin",
    "Ostrzeżenia skanowania": "Scan warnings",
    "Platforma": "Platform",
    "Python": "Python",
    "Tryb": "Mode",
    "paczka EXE": "packaged EXE",
    "źródła": "source",
    "Zdjęcia": "Photos",
    "Grupy dokładne": "Exact groups",
    "Grupy podobne": "Similar groups",
    "Ostrzeżenia": "Warnings",
    "Zaznaczone do kosza": "Marked for Recycle Bin",
    "Skan anulowany": "Scan cancelled",
    "tak": "yes",
    "nie": "no",
    "To okno niczego nie usuwa automatycznie. Test Kosza używa wyłącznie dwóch małych plików PNG wygenerowanych przez SWIR PhotoClean.": "This window never deletes anything automatically. The Recycle Bin check uses only two small PNG files generated by SWIR PhotoClean.",
    "Preflight Kosza": "Recycle Bin preflight",
    "gotowy": "ready",
    "zablokowany": "blocked",
    "Szczegóły": "Details",
    "Przygotuj pliki testowe…": "Prepare test files…",
    "Wznów test z manifestu…": "Resume test from manifest…",
    "Przenieś wygenerowaną kopię do Kosza": "Move generated copy to Recycle Bin",
    "Sprawdź przywróconą kopię": "Verify restored copy",
    "Utwórz RELEASE_EVIDENCE…": "Create RELEASE_EVIDENCE…",
    "Otwórz folder testu": "Open test folder",
    "Kopiuj ścieżkę dowodu": "Copy evidence path",
    "Kopiuj ścieżkę raportu": "Copy report path",
    "Kopiuj ścieżkę RELEASE_EVIDENCE": "Copy RELEASE_EVIDENCE path",
    "Zamknij": "Close",
    "Wybierz lokalny folder na pliki testowe": "Choose a local folder for generated test files",
    "Wybierz manifest testu Kosza": "Choose Recycle Bin evidence manifest",
    "Test Kosza wymaga lokalnego dysku stałego i dostępnych komponentów Windows.": "The Recycle Bin check requires a local fixed drive and available Windows components.",
    "Przygotowano test w: {v0}": "Prepared verification in: {v0}",
    "Przeniesienie testowej kopii": "Move generated test copy",
    "Do Kosza zostanie przeniesiony WYŁĄCZNIE plik RECYCLE-ME.png utworzony przez program. KEEP-ME.png pozostanie na miejscu. Kontynuować?": "ONLY RECYCLE-ME.png generated by the app will be moved to the Recycle Bin. KEEP-ME.png will remain in place. Continue?",
    "Nie udało się wykonać testu Kosza": "Recycle Bin check failed",
    "Kopia trafiła do Kosza, a oryginał pozostał na miejscu. Teraz przywróć RECYCLE-ME.png ręcznie z Kosza Windows do folderu testowego i kliknij „Sprawdź przywróconą kopię”.": "The copy reached the Recycle Bin and the original stayed in place. Restore RECYCLE-ME.png manually from the Windows Recycle Bin to the test folder, then click “Verify restored copy”.",
    "Przywracanie potwierdzone": "Restore verified",
    "Raport dowodu gotowy: {v0}": "Evidence report ready: {v0}",
    "Przywrócenie jest już potwierdzone. Kliknij „Sprawdź przywróconą kopię”, aby bez ponownego testu odtworzyć i zweryfikować raport dowodu.": "The restore is already verified. Click “Verify restored copy” to recreate and validate the evidence report without repeating the physical test.",
    "Potwierdzono przywrócenie identycznej kopii SHA-256 przy zachowaniu oryginału. Raport dowodu został ponownie zweryfikowany i jest gotowy do ręcznego przeglądu akceptacyjnego: {v0}": "Verified restoration of the identical SHA-256 copy while preserving the original. The evidence report was freshly validated and is ready for manual acceptance review: {v0}",
    "Potwierdzenie ręcznego przywrócenia": "Manual restore confirmation",
    "Potwierdzam, że ręcznie przywróciłem RECYCLE-ME.png z Kosza Windows. Program ponownie zweryfikuje raport i utworzy RELEASE_EVIDENCE.json. Ten krok nie zamyka checklisty STATUS.md ani nie publikuje wydania. Kontynuować?": "I confirm that I manually restored RECYCLE-ME.png from the Windows Recycle Bin. The app will revalidate the report and create RELEASE_EVIDENCE.json. This step does not close STATUS.md or publish a release. Continue?",
    "Nie udało się utworzyć dowodu wydania": "Could not create release evidence",
    "Dowód wydania gotowy": "Release evidence ready",
    "RELEASE_EVIDENCE gotowy: {v0}": "RELEASE_EVIDENCE ready: {v0}",
    "Utworzono i ponownie zweryfikowano RELEASE_EVIDENCE.json. Plik nadal zawiera acceptance_gate_closed=false i wymaga ręcznego przeglądu przed zmianą STATUS.md lub publikacją: {v0}": "Created and revalidated RELEASE_EVIDENCE.json. It still contains acceptance_gate_closed=false and requires manual review before changing STATUS.md or publishing: {v0}",
    "Brak aktywnego testu Kosza.": "No active Recycle Bin verification.",
    "Nie można otworzyć folderu": "Cannot open folder",
    "Brak ostrzeżeń z bieżącego skanu.": "No warnings from the current scan.",
    "Lokalny dowód nie zmienia automatycznie checklisty repozytorium. Ten przebieg jest wiązany z bieżącym kontraktem bezpieczeństwa wydania; po ręcznym Restore program tworzy i ponownie weryfikuje raport przed przeglądem bramki 1.0.": "Local evidence never changes the repository checklist automatically. This run is bound to the current release safety contract; after manual Restore the app creates and freshly validates the report before 1.0 gate review.",
}


def diag_tr(message, **values):
    text = DIAG_EN.get(message, message) if i18n.language == "en" else message
    return text.format(**values) if values else text


class DiagnosticsWindow:
    """Read-only status plus an explicit, release-qualified restore verification flow."""

    def __init__(self, app: "PhotoCleanApp"):
        self.app = app
        self.snapshot = build_diagnostics_snapshot(app.result, len(app.marked))
        self.check: RecycleVerification | None = None
        self.evidence_report: Path | None = None
        self.release_attestation: Path | None = None

        self.window = tk.Toplevel(app.root)
        self.window.title(diag_tr("Centrum diagnostyki"))
        self.window.geometry("900x620")
        self.window.minsize(720, 480)
        self.window.configure(bg=BG)
        self.window.transient(app.root)

        outer = ttk.Frame(self.window, padding=14)
        outer.pack(fill="both", expand=True)
        ttk.Label(
            outer,
            text=diag_tr(
                "To okno niczego nie usuwa automatycznie. Test Kosza używa wyłącznie dwóch małych plików PNG wygenerowanych przez SWIR PhotoClean."
            ),
            wraplength=840,
        ).pack(anchor="w", pady=(0, 10))

        notebook = ttk.Notebook(outer)
        notebook.pack(fill="both", expand=True)
        overview = ttk.Frame(notebook, padding=12)
        recycle = ttk.Frame(notebook, padding=12)
        warnings = ttk.Frame(notebook, padding=12)
        notebook.add(overview, text=diag_tr("Przegląd"))
        notebook.add(recycle, text=diag_tr("Kosz Windows"))
        notebook.add(warnings, text=diag_tr("Ostrzeżenia skanowania"))

        self._build_overview(overview)
        self._build_recycle(recycle)
        self._build_warnings(warnings)

        footer = ttk.Frame(outer, padding=(0, 10, 0, 0))
        footer.pack(fill="x")
        ttk.Button(footer, text=diag_tr("Zamknij"), command=self.window.destroy).pack(side="right")
        self.window.bind("<Escape>", lambda event: self.window.destroy())

    def _build_overview(self, parent):
        rows = (
            (diag_tr("Platforma"), self.snapshot.platform),
            (diag_tr("Python"), self.snapshot.python),
            (diag_tr("Tryb"), diag_tr("paczka EXE") if self.snapshot.frozen else diag_tr("źródła")),
            (diag_tr("Zdjęcia"), str(self.snapshot.photo_count)),
            (diag_tr("Grupy dokładne"), str(self.snapshot.exact_group_count)),
            (diag_tr("Grupy podobne"), str(self.snapshot.similar_group_count)),
            (diag_tr("Ostrzeżenia"), str(self.snapshot.warning_count)),
            (diag_tr("Zaznaczone do kosza"), str(self.snapshot.marked_count)),
            (diag_tr("Skan anulowany"), diag_tr("tak") if self.snapshot.cancelled else diag_tr("nie")),
        )
        table = ttk.Frame(parent)
        table.pack(anchor="nw", fill="x")
        for row, (label, value) in enumerate(rows):
            ttk.Label(table, text=label).grid(row=row, column=0, sticky="w", padx=(0, 18), pady=4)
            ttk.Label(table, text=value).grid(row=row, column=1, sticky="w", pady=4)

    def _build_recycle(self, parent):
        support = inspect_recycle_support(Path.home())
        ready_text = diag_tr("gotowy") if support.ready else diag_tr("zablokowany")
        ttk.Label(parent, text=f"{diag_tr('Preflight Kosza')}: {ready_text}").pack(anchor="w")
        ttk.Label(parent, text=f"{diag_tr('Szczegóły')}: {support.detail}", wraplength=820).pack(anchor="w", pady=(2, 10))
        ttk.Label(
            parent,
            text=diag_tr(
                "Lokalny dowód nie zmienia automatycznie checklisty repozytorium. Ten przebieg jest wiązany z bieżącym kontraktem bezpieczeństwa wydania; po ręcznym Restore program tworzy i ponownie weryfikuje raport przed przeglądem bramki 1.0."
            ),
            wraplength=820,
        ).pack(anchor="w", pady=(0, 10))

        self.recycle_status = tk.StringVar(value=diag_tr("Brak aktywnego testu Kosza."))
        ttk.Label(parent, textvariable=self.recycle_status, wraplength=820).pack(anchor="w", pady=(0, 10))

        buttons = ttk.Frame(parent)
        buttons.pack(fill="x", pady=(0, 8))
        self.prepare_button = ttk.Button(buttons, text=diag_tr("Przygotuj pliki testowe…"), command=self.prepare_check)
        self.prepare_button.pack(side="left")
        self.move_button = ttk.Button(
            buttons,
            text=diag_tr("Przenieś wygenerowaną kopię do Kosza"),
            command=self.move_check,
            state="disabled",
        )
        self.move_button.pack(side="left", padx=8)
        self.verify_button = ttk.Button(
            buttons,
            text=diag_tr("Sprawdź przywróconą kopię"),
            command=self.verify_check,
            state="disabled",
        )
        self.verify_button.pack(side="left")

        secondary = ttk.Frame(parent)
        secondary.pack(fill="x")
        self.resume_button = ttk.Button(
            secondary,
            text=diag_tr("Wznów test z manifestu…"),
            command=self.resume_check,
        )
        self.resume_button.pack(side="left")
        self.open_button = ttk.Button(secondary, text=diag_tr("Otwórz folder testu"), command=self.open_folder, state="disabled")
        self.open_button.pack(side="left", padx=8)

        release_row = ttk.Frame(parent)
        release_row.pack(fill="x", pady=(8, 0))
        self.attest_button = ttk.Button(
            release_row,
            text=diag_tr("Utwórz RELEASE_EVIDENCE…"),
            command=self.attest_check,
            state="disabled",
        )
        self.attest_button.pack(side="left")
        self.copy_button = ttk.Button(
            release_row,
            text=diag_tr("Kopiuj ścieżkę dowodu"),
            command=self.copy_evidence_path,
            state="disabled",
        )
        self.copy_button.pack(side="left", padx=8)

    def _build_warnings(self, parent):
        if not self.app.result.warnings:
            ttk.Label(parent, text=diag_tr("Brak ostrzeżeń z bieżącego skanu.")).pack(anchor="w")
            return
        frame = ttk.Frame(parent)
        frame.pack(fill="both", expand=True)
        text = tk.Text(frame, wrap="word", height=18, bg="#10182a", fg="#eef4ff", relief="flat")
        scroll = ttk.Scrollbar(frame, orient="vertical", command=text.yview)
        text.configure(yscrollcommand=scroll.set)
        text.pack(side="left", fill="both", expand=True)
        scroll.pack(side="right", fill="y")
        text.insert("1.0", "\n".join(self.app.result.warnings))
        text.configure(state="disabled")

    def _apply_check_state(self, check: RecycleVerification, report: Path | None = None):
        if check.stage not in {"prepared", "recycled", "restored-verified"}:
            raise RecycleVerificationError(f"Unsupported recycle verification stage: {check.stage}")

        self.check = check
        self.evidence_report = report
        self.release_attestation = None
        self.open_button.configure(state="normal")
        self.attest_button.configure(
            state="normal" if check.stage == "restored-verified" and report is not None else "disabled"
        )
        self.copy_button.configure(
            text=diag_tr("Kopiuj ścieżkę raportu") if report is not None else diag_tr("Kopiuj ścieżkę dowodu"),
            state="normal",
        )

        if check.stage == "prepared":
            self.move_button.configure(state="normal")
            self.verify_button.configure(state="disabled")
            self.recycle_status.set(diag_tr("Przygotowano test w: {v0}", v0=check.folder))
            return

        self.move_button.configure(state="disabled")
        if check.stage == "recycled":
            self.verify_button.configure(state="normal")
            self.recycle_status.set(
                diag_tr(
                    "Kopia trafiła do Kosza, a oryginał pozostał na miejscu. Teraz przywróć RECYCLE-ME.png ręcznie z Kosza Windows do folderu testowego i kliknij „Sprawdź przywróconą kopię”."
                )
            )
            return

        if report is not None:
            self.verify_button.configure(state="disabled")
            self.recycle_status.set(diag_tr("Raport dowodu gotowy: {v0}", v0=report))
        else:
            self.verify_button.configure(state="normal")
            self.recycle_status.set(
                diag_tr(
                    "Przywrócenie jest już potwierdzone. Kliknij „Sprawdź przywróconą kopię”, aby bez ponownego testu odtworzyć i zweryfikować raport dowodu."
                )
            )

    def prepare_check(self):
        base = filedialog.askdirectory(title=diag_tr("Wybierz lokalny folder na pliki testowe"), parent=self.window)
        if not base:
            return
        support = inspect_recycle_support(base)
        if not support.ready:
            messagebox.showwarning(
                diag_tr("Centrum diagnostyki"),
                diag_tr("Test Kosza wymaga lokalnego dysku stałego i dostępnych komponentów Windows.") + f"\n\n{support.detail}",
                parent=self.window,
            )
            return
        try:
            check = create_restore_evidence(base)
            self._apply_check_state(check)
        except (OSError, RecycleVerificationError) as error:
            messagebox.showerror(diag_tr("Nie udało się wykonać testu Kosza"), str(error), parent=self.window)

    def resume_check(self):
        manifest = filedialog.askopenfilename(
            title=diag_tr("Wybierz manifest testu Kosza"),
            parent=self.window,
            filetypes=(("JSON", "*.json"), ("All files", "*.*")),
        )
        if not manifest:
            return
        try:
            check = load_recycle_verification(Path(manifest).expanduser().resolve())
            _require_runtime_safety_contract(check)
            report = None
            if check.stage == "restored-verified":
                candidate = check.folder / REPORT_NAME
                if candidate.is_file():
                    validate_restore_evidence_report(candidate, manifest=check.manifest)
                    report = candidate
            self._apply_check_state(check, report)
        except (OSError, RecycleVerificationError) as error:
            messagebox.showerror(diag_tr("Nie udało się wykonać testu Kosza"), str(error), parent=self.window)

    def move_check(self):
        if self.check is None:
            return
        if not messagebox.askyesno(
            diag_tr("Przeniesienie testowej kopii"),
            diag_tr(
                "Do Kosza zostanie przeniesiony WYŁĄCZNIE plik RECYCLE-ME.png utworzony przez program. KEEP-ME.png pozostanie na miejscu. Kontynuować?"
            ),
            parent=self.window,
        ):
            return
        try:
            check = move_restore_evidence(self.check.manifest)
            self._apply_check_state(check)
        except (OSError, RecycleVerificationError) as error:
            messagebox.showerror(diag_tr("Nie udało się wykonać testu Kosza"), str(error), parent=self.window)

    def verify_check(self):
        if self.check is None:
            return
        try:
            verified, report = verify_restore_evidence(self.check.manifest)
            validate_restore_evidence_report(report, manifest=verified.manifest)
            self._apply_check_state(verified, report)
        except (OSError, RecycleVerificationError) as error:
            messagebox.showerror(diag_tr("Nie udało się wykonać testu Kosza"), str(error), parent=self.window)
            return

        messagebox.showinfo(
            diag_tr("Przywracanie potwierdzone"),
            diag_tr(
                "Potwierdzono przywrócenie identycznej kopii SHA-256 przy zachowaniu oryginału. Raport dowodu został ponownie zweryfikowany i jest gotowy do ręcznego przeglądu akceptacyjnego: {v0}",
                v0=report,
            ),
            parent=self.window,
        )

    def attest_check(self):
        if self.check is None or self.evidence_report is None:
            return
        if not messagebox.askyesno(
            diag_tr("Potwierdzenie ręcznego przywrócenia"),
            diag_tr(
                "Potwierdzam, że ręcznie przywróciłem RECYCLE-ME.png z Kosza Windows. Program ponownie zweryfikuje raport i utworzy RELEASE_EVIDENCE.json. Ten krok nie zamyka checklisty STATUS.md ani nie publikuje wydania. Kontynuować?"
            ),
            parent=self.window,
        ):
            return

        target = self.check.folder / ATTESTATION_NAME
        try:
            written = write_packaged_attestation(
                self.evidence_report,
                target,
                confirm_manual_restore=True,
            )
        except (OSError, PackagedAttestationError, RecycleVerificationError) as error:
            messagebox.showerror(
                diag_tr("Nie udało się utworzyć dowodu wydania"),
                str(error),
                parent=self.window,
            )
            return

        self.release_attestation = written
        self.attest_button.configure(state="disabled")
        self.copy_button.configure(
            text=diag_tr("Kopiuj ścieżkę RELEASE_EVIDENCE"),
            state="normal",
        )
        self.recycle_status.set(diag_tr("RELEASE_EVIDENCE gotowy: {v0}", v0=written))
        messagebox.showinfo(
            diag_tr("Dowód wydania gotowy"),
            diag_tr(
                "Utworzono i ponownie zweryfikowano RELEASE_EVIDENCE.json. Plik nadal zawiera acceptance_gate_closed=false i wymaga ręcznego przeglądu przed zmianą STATUS.md lub publikacją: {v0}",
                v0=written,
            ),
            parent=self.window,
        )

    def open_folder(self):
        if self.check is None:
            return
        try:
            if os.name != "nt":
                raise OSError("Windows required")
            os.startfile(str(self.check.folder))
        except OSError as error:
            messagebox.showerror(diag_tr("Nie można otworzyć folderu"), str(error), parent=self.window)

    def copy_evidence_path(self):
        if self.check is None:
            return
        target = self.release_attestation or self.evidence_report or self.check.manifest
        self.app.root.clipboard_clear()
        self.app.root.clipboard_append(str(target))


class PhotoCleanApp(SpaceHunterPhotoCleanApp):
    """Final desktop layer with diagnostics and safe acceptance-test helpers."""

    def _install_session_menu(self):
        super()._install_session_menu()
        self.view_menu.add_separator()
        self.view_menu.add_command(
            label=diag_tr("Centrum diagnostyki…"),
            command=self.open_diagnostics,
            accelerator=diag_tr("Ctrl+Shift+D"),
        )
        self.root.bind("<Control-Shift-D>", lambda event: self.open_diagnostics())
        self.root.bind("<Control-Shift-d>", lambda event: self.open_diagnostics())

    def open_diagnostics(self):
        existing = getattr(self, "diagnostics_view", None)
        if existing is not None and existing.window.winfo_exists():
            existing.window.lift()
            return
        self.diagnostics_view = DiagnosticsWindow(self)


def main():
    if os.name == "nt":
        import ctypes

        try:
            ctypes.windll.shcore.SetProcessDpiAwareness(1)
        except (AttributeError, OSError):
            pass
    root = tk.Tk()
    PhotoCleanApp(root)
    root.mainloop()
